name : CI
on   : [push, pull_request]
jobs :
    "Linting":
        runs-on : ubuntu-latest
        steps   :
            - uses: actions/checkout@v2
            - uses: actions/setup-node@v2
              with:
                node-version: '14'
            - run: yarn install
            - run: yarn lint --max-warnings 0 --color
