name : Publication
on:
    workflow_dispatch: null
    push:
        tags: ['*']
jobs:
    publish:
        runs-on : ubuntu-latest
        steps   :
            - uses: actions/checkout@v2
            - uses: actions/setup-node@v1
            - run: yarn install
            - run: yarn build
            - run: yarn publish
              env:
                NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
    publish-doc:
        needs   : publish
        runs-on : ubuntu-latest
        steps   :
            - uses: actions/checkout@v2
              with:
                persist-credentials: false
            - uses: actions/setup-node@v1
            - run: yarn install
            - run: yarn build:doc
            - uses : JamesIves/github-pages-deploy-action@3.7.1
              with :
                GITHUB_TOKEN : ${{ secrets.GITHUB_TOKEN }}
                BRANCH       : gh-pages
                FOLDER       : sassdoc
                CLEAN        : true
